name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install swiftlint
      run: brew install swiftlint
    - name: Build
      run: swift build -v
    - name: Run lint
      run: swiftlint --strict
    - name: Run tests
      run: swift test -v

